CREATE TABLE PRODUCT (
    PROD_NO NUMBER(4), QUANTITY NUMBER(5, 2), UNIT_PRICE NUMBER(7, 2), DISCOUNT NUMBER(3, 1), TAX NUMBER(4, 2), TOTAL_PRICE NUMBER (7, 2)
);

DROP TABLE PRODUCT;

INSERT INTO PRODUCT VALUES(
    100, 1.756, 150, 5.5, 18, 325.32
);

INSERT INTO PRODUCT VALUES(
    200, 1.500, 120, NULL, NULL, 180
);

INSERT INTO PRODUCT VALUES(
    300, NULL, 300, NULL, NULL, NULL
);

INSERT INTO PRODUCT VALUES(
    400, NULL, NULL, NULL, NULL, NULL
);

SELECT *
FROM PRODUCT;

UPDATE PRODUCT
SET
    DISCOUNT=10
WHERE
    PROD_NO=200;

UPDATE PRODUCT
SET
    TAX=12
WHERE
    PROD_NO=200;

UPDATE PRODUCT
SET
    QUANTITY=1.250
WHERE
    PROD_NO=300;

UPDATE PRODUCT
SET
    TAX=5
WHERE
    PROD_NO=300;

UPDATE PRODUCT
SET
    DISCOUNT=0
WHERE
    PROD_NO=300;

UPDATE PRODUCT
SET
    TOTAL_PRICE=300*1.25-0.05
WHERE
    PROD_NO=300;

COMMIT;

DELETE FROM PRODUCT
WHERE
    PROD_NO=400;

UPDATE PRODUCT
SET
    DISCOUNT=NULL;

SELECT *
FROM PRODUCT;

SELECT PROD_NO, QUANTITY, UNIT_PRICE, TOTAL_PRICE
FROM PRODUCT;

SELECT *
FROM PRODUCT
WHERE PROD_NO=100;

SELECT PROD_NO, TOTAL_PRICE
FROM PRODUCT
WHERE PROD_NO=100 OR PROD_NO=300;