CREATE TABLE STUDENT (
    SNO NUMBER(3)   CONSTRAINT STU_SNO_NN NOT NULL,
    SNAME VARCHAR2(10) CONSTRAINT STU_SNA_NN NOT NULL,
    MSQL NUMBER(3) CONSTRAINT STU_MSQL_CK CHECK(MSQL BETWEEN 0 AND 100)
);

CREATE TABLE BILL (
    bill_no NUMBER(3),
    item_no NUMBER(3),
    item_name NUMBER(10) ,
    unit_price NUMBER(4), 
    discount NUMBER(3),
    CONSTRAINT BILL_DIS_CK CHECK(DISCOUNT< 0.1*UNIT_PRICE)
);

SELECT  CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='STUDENT' OR TABLE_NAME='BILL' ;

CREATE TABLE ACCOUNT (
    ACNO NUMBER(10) CONSTRAINT ACC_AN_PK PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(10),
    ACCOUNT_TYPE VARCHAR2(10),
    BALANCE NUMBER(6),
    aadhar_no NUMBER(12) CONSTRAINT ACC_AA_NN NOT NULL,
    CONSTRAINT ACC_AA_UK UNIQUE(aadhar_no),
    pan NUMBER(10) CONSTRAINT ACC_PA_UK UNIQUE
);
CREATE TABLE TRANSACTION (
    ACNO NUMBER(10) CONSTRAINT TR_AN_FK REFERENCES ACCOUNT(ACNO),
    TRANSACTION_AMT NUMBER(4),
    TRANSACTION_TYPE VARCHAR2(10)
);

ALTER TABLE ACCOUNT 
ADD CONSTRAINT ACC_AT_CK CHECK(ACCOUNT_TYPE IN ('SB','CA'));

SELECT  CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ACCOUNT' OR TABLE_NAME='TRANSACTION' ;