CREATE TABLE T3(
        N NUMBER
    );


INSERT into T3 VALUES(
    1000
);
INSERT into T3 VALUES(
    1000.333
);
INSERT into T3 VALUES(
    1000.123
);
INSERT into T3 VALUES(
    5.1
);


SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE SALARY <= 5000 AND DEPARTMENT_ID <= 60;

SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM EMPLOYEES
WHERE NOT (SALARY > 5000 or DEPARTMENT_ID > 60);


CREATE TABLE t2(
    ENO NUMBER(3),
    SALARY NUMBER(5)
);

INSERT INTO T2 VALUES (100,1000);
INSERT INTO T2 VALUES (200,1000);
INSERT INTO T2 VALUES (100,1000);
INSERT INTO T2 VALUES (100,1000);
INSERT INTO T2 VALUES (100,1000);
INSERT INTO T2 VALUES (100,1000);
INSERT INTO T2 VALUES (100,1000);


SELECT min(ROWID)
FROM T2
GROUP BY ENO;

SELECT *
FROM T2
WHERE ROWID='AAAR1WAAEAAAJVVAAB' OR ROWID='AAAR1WAAEAAAJVVAAA';

SELECT FIRST_NAME, LAST_NAME, SALARY, round(SALARY*0.18) as INCENTIVE_RS, (SALARY*0.18 -  round(SALARY*0.18))*100 as INCENTIVE_PS
FROM  EMPLOYEES;

CREATE TABLE SALES(
     PROD_ID CHAR(15),
     PROD_TITLE VARCHAR2(10),
     PROD_SUMMARY VARCHAR2(20),
     PROD_TYPE CHAR(2),
     UNIT_PRICE NUMBER(4)
);



