SELECT *
FROM REGIONS
ORDER BY REGION_NAME DESC;
-- REGION_ID,REGION_NAME
-- 4,Middle East and Africa
-- 1,Europe
-- 3,Asia
-- 2,Americas

SELECT MANAGER_ID, DEPARTMENT_ID
FROM EMPLOYEES
order by MANAGER_ID;
-- MANAGER_ID,DEPARTMENT_ID
-- 149,80
-- 149,80
-- 149,80
-- 149,80
-- 201,20
-- 205,110
--     ,90


SELECT FIRST_NAME,LAST_NAME
FROM EMPLOYEES
ORDER BY 1,2;
-- FIRST_NAME,LAST_NAME
-- Adam,Fripp
-- Alana,Walsh
-- Alberto,Errazuriz
-- Alexander,Hunold
-- Alexander,Khoo

SELECT DEPARTMENT_ID, COUNT(*)
FROM employees
GROUP BY DEPARTMENT_ID;

-- DEPARTMENT_ID,COUNT(*)
-- 50,45
-- 40,1

SELECT DEPARTMENT_ID, COUNT(*)
FROM employees
GROUP BY DEPARTMENT_ID
ORDER BY 2;
-- DEPARTMENT_ID,COUNT(*)
-- 70,1
-- 10,1
--   ,1
-- 40,1
-- 110,2


SELECT DEPARTMENT_ID, COUNT(*) AS EMP_COUNT, SUM(SALARY) AS DEP_TOT_SAL
FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)> 25
ORDER BY DEPARTMENT_ID;
-- DEPARTMENT_ID,EMP_COUNT,DEP_TOT_SAL
-- 50,45,156400
-- 80,34,304500


SELECT distinct DEPARTMENT_ID
from EMPLOYEES
WHERE DEPARTMENT_ID IS NOT NULL AND SALARY>10000;
-- DEPARTMENT_ID
-- 110
-- 90
-- 30
-- 20
-- 100
-- 80