CREATE TABLE POOL_A (
    TEAM VARCHAR2(20)
);
CREATE TABLE POOL_B (
    TEAM VARCHAR2(20)
);
INSERT INTO POOL_A VALUES(
    &&3
);
INSERT INTO POOL_B VALUES(
    &&5
);
COMMIT;
select *From pool_a;
TEAM
--------------------
SA

ENG
AUS
select *From pool_b;
TEAM
--------------------
IND
SL
select *
from pool_a 
cross join pool_b;
TEAM TEAM
-------------------- --------------------
SA IND
ENG IND
AUS IND
SA SL

--INNER JOINS
SELECT DEPARTMENT_NAME, FIRST_NAME, LAST_NAME
FROM DEPARTMENTS
INNER JOIN  EMPLOYEES
ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID;
-- DEPARTMENT_NAME,FIRST_NAME,LAST_NAME
-- Administration,Jennifer,Whalen
-- Marketing,Pat,Fay
-- Marketing,Michael,Hartstein

--NATURAL JOINS
SELECT *
FROM REGIONS
NATURAL JOIN COUNTRIES;
--REGION_ID,REGION_NAME,COUNTRY_ID,COUNTRY_NAME
-- 4,Middle East and Africa,ZM,Zambia
-- 4,Middle East and Africa,EG,Egypt
-- 4,Middle East and Africa,ZW,Zimbabwe
-- 4,Middle East and Africa,NG,Nigeria
-- 4,Middle East and Africa,KW,Kuwait

--USING KEYWORD
SELECT *
FROM DEPARTMENTS
JOIN EMPLOYEES
USING (DEPARTMENT_ID,MANAGER_ID);
--DEPARTMENT_ID,MANAGER_ID,DEPARTMENT_NAME,LOCATION_ID,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT
-- 20,201,Marketing,1800,202,Pat,Fay,PFAY,603.123.6666,17-AUG-05,MK_REP,6000,
-- 110,205,Accounting,1700,206,William,Gietz,WGIETZ,515.123.8181,07-JUN-02,AC_ACCOUNT,8300,

--INEQUI JOINS
SELECT FIRST_NAME,LAST_NAME,L.JOB_ID,R.SALARY,L.MIN_SALARY,L.MAX_SALARY
FROM JOBS L
JOIN EMPLOYEES R
ON R.SALARY BETWEEN L.MIN_SALARY AND L.MAX_SALARY;
--FIRST_NAME,LAST_NAME,JOB_ID,SALARY,MIN_SALARY,MAX_SALARY
-- TJ,Olson,ST_CLERK,2100,2008,5000
-- Steven,Markle,ST_CLERK,2200,2008,5000
-- Hazel,Philtanker,ST_CLERK,2200,2008,5000

--SELF JOIN
SELECT L.FIRST_NAME,L.LAST_NAME,L.SALARY,
       R.FIRST_NAME,R.LAST_NAME,R.SALARY
FROM EMPLOYEES L
JOIN EMPLOYEES R
ON L.SALARY> R.SALARY;
--FIRST_NAME,LAST_NAME,SALARY,FIRST_NAME,LAST_NAME,SALARY
-- Steven,King,24000,Neena,Kochhar,17000
-- Steven,King,24000,Lex,De Haan,17000
-- ..
-- Karen,Partners,13500,Sigal,Tobias,2800
-- Karen,Partners,13500,Vance,Jones,2800

SELECT L.FIRST_NAME,L.LAST_NAME,L.COMMISSION_PCT,
       R.FIRST_NAME,R.LAST_NAME,R.COMMISSION_PCT
FROM EMPLOYEES L
JOIN EMPLOYEES R
ON L.COMMISSION_PCT> R.COMMISSION_PCT;

--OUTER LEFT JOINS
SELECT L.DEPARTMENT_NAME, R.FIRST_NAME, R.LAST_NAME
FROM DEPARTMENTS L
LEFT OUTER JOIN  EMPLOYEES R
ON L.DEPARTMENT_ID=R.DEPARTMENT_ID;

--RIGHT OUTER JOIN
SELECT L.DEPARTMENT_NAME, R.FIRST_NAME, R.LAST_NAME
FROM DEPARTMENTS L
RIGHT OUTER JOIN  EMPLOYEES R
ON L.DEPARTMENT_ID=R.DEPARTMENT_ID;

--FULL OUTER JOIN
SELECT L.DEPARTMENT_NAME, R.FIRST_NAME, R.LAST_NAME
FROM DEPARTMENTS L
FULL OUTER JOIN  EMPLOYEES 
ON L.DEPARTMENT_ID=R.DEPARTMENT_ID;

--3 TABLE JOIN
SELECT R.REGION_NAME,C.COUNTRY_NAME,L.CITY
FROM REGIONS R 
    JOIN COUNTRIES C
        ON R.REGION_ID=C.REGION_ID 
    JOIN LOCATIONS L
        ON C.COUNTRY_ID=L.COUNTRY_ID;

SELECT R.REGION_NAME,C.COUNTRY_NAME,L.CITY
FROM REGIONS R 
    LEFT JOIN COUNTRIES C
        ON R.REGION_ID=C.REGION_ID 
    LEFT JOIN LOCATIONS L
        ON C.COUNTRY_ID=L.COUNTRY_ID;

--5 TABLE JOIN
SELECT R.REGION_NAME,C.COUNTRY_NAME,L.CITY,D.DEPARTMENT_ID,E.FIRST_NAME,E.LAST_NAME
FROM REGIONS R 
    JOIN COUNTRIES C
        ON R.REGION_ID=C.REGION_ID 
    JOIN LOCATIONS L
        ON C.COUNTRY_ID=L.COUNTRY_ID
    JOIN DEPARTMENTS D
        ON L.LOCATION_ID=D.LOCATION_ID
    JOIN EMPLOYEES E
        ON D.DEPARTMENT_ID=E.DEPARTMENT_ID;

--JOINING WITH FILTER CONDITION USING "WHERE" AND USING "ON"
SELECT D.DEPARTMENT_ID,E.FIRST_NAME,E.LAST_NAME,J.JOB_TITLE
FROM DEPARTMENTS D
    INNER JOIN EMPLOYEES E
        ON D.DEPARTMENT_ID=E.DEPARTMENT_ID
    INNER JOIN JOBS J
        ON E.JOB_ID=J.JOB_ID
WHERE D.DEPARTMENT_ID=20;

SELECT D.DEPARTMENT_ID, E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE
FROM DEPARTMENTS D
    INNER JOIN EMPLOYEES E
        ON D.DEPARTMENT_ID=20 AND D.DEPARTMENT_ID=E.DEPARTMENT_ID
    INNER JOIN JOBS J
        ON E.JOB_ID=J.JOB_ID;
--DEPARTMENT_ID,FIRST_NAME,LAST_NAME,JOB_TITLE
-- 20,Michael,Hartstein,Marketing Manager
-- 20,Pat,Fay,Marketing Representative


