SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;

SELECT *
FROM EMPLOYEES
WHERE SALARY BETWEEN 6000 AND 12000;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (60, 80, 90);

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%MAN';

SELECT DEPART
FROM EMPLOYEES
WHERE JOB_ID LIKE '%\_%' ESCAPE'\';

SELECT JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%\_%' ESCAPE'\';

SELECT COUNTRY_ID, COUNTRY_NAME
FROM COUNTRIES
WHERE REGION_ID != 2;

SELECT *
FROM EMPLOYEES
WHERE NOT JOB_ID LIKE '%CLERK%';

SELECT DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE MANAGER_ID IS NULL;

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%CLERK%' AND SALARY>1000;

SELECT *
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%CLERK%' AND JOB_ID NOT LIKE '%MAN%' AND DEPARTMENT_ID NOT IN (100, 110, 10, 20);

SELECT *
FROM EMPLOYEES
WHERE JOB_ID LIKE '%REP%' OR SALARY BETWEEN 5000 AND 10000;

SELECT *
FROM EMPLOYEES FETCH FIRST 5 ROWS ONLY;

--CHECK
ALTER table EMPLOYEE1 
ADD CONSTRAINT EMP1_SAL_CK CHECK(SALARY BETWEEN 10000 AND 90000);
ALTER table EMPLOYEE1 
ADD CONSTRAINT EMP1_SAL_CK NOT NULL(EMPID);
ALTER table EMPLOYEE1 
ADD CONSTRAINT EMP1_HRA_CK CHECK(HRA<0.2*BASIC);

SELECT *
FROM EMPLOYEE1;
INSERT INTO EMPLOYEE1 VALUES (
    3, 50000,2000,300
);


DESC EMPLOYEE1;

--UNIQUE
ALTER TABLE EMP3
ADD CONSTRAINT EMP3_PASSPORTNO_UK UNIQUE(PASSPORT_NO);

-- FK constraint
CREATE TABLE team_lead (
    tl_no NUMBER(5) CONSTRAINT tl_pk PRIMARY KEY,
    tl_name VARCHAR2(10)  
);

CREATE TABLE member_table (
    emp_no NUMBER(5),
    emp_name VARCHAR2(10),
    tl_no NUMBER(5) CONSTRAINT mem_fk REFERENCES team_lead(tl_no)
    on DELETE set NULL
);

INSERT INTO team_lead values (
    100, 'AAA'
);
INSERT INTO member_table values (
    101, 'xxx', 100
);


-- self-integrity constraint
CREATE TABLE emp4 (
    eno number(5) CONSTRAINT e4_pk PRIMARY KEY,
    ename VARCHAR2(10),
    designation VARCHAR2(10),
    MANAGER_ID CONSTRAINT e4_fk REFERENCES emp4(eno)
);

INSERT INTO emp4 VALUES (
    100, 'AAA', 'President', NULL
);
INSERT INTO emp4 VALUES (
    101, 'AAA', 'Fin dir', 100
);
SELECT *
from member_table;